# Generated by Django 4.0.4 on 2022-06-02 09:14

from django.db import migrations, models
import dropbox.base


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgallarymodel',
            name='image_gallary',
            field=models.ImageField(upload_to=dropbox.base.DropboxBase.files_upload, verbose_name='image_gallary'),
        ),
    ]
