# Generated by Django 4.0.4 on 2022-06-02 10:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=accounts.models.upload_to),
        ),
    ]
