# Generated by Django 4.0.4 on 2022-06-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='loyal_customer_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mid_month_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
